# Generated by Django 4.1.3 on 2022-11-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INN', models.BigIntegerField()),
                ('registration_date', models.DateField()),
                ('region', models.TextField()),
                ('okved', models.TextField()),
                ('industry', models.TextField()),
                ('section', models.TextField()),
            ],
        ),
    ]
